baseURL = "https://superluminar.io/"
languageCode = "de-de"
title = "superluminar GmbH"
theme = "superluminar"
disqusShortname = "superluminar"
enableRobotsTXT = true

[params]
gaTrackingId = "UA-110302159-1"

[permalinks]
post = "/:year/:month/:day/:title/"
